version: "3"

services:
  redroid:
    image: redroid/redroid:11.0.0-latest
    restart: always
    volumes:
      - ./data:/data
    ports: 
      - "5555:5555"
    privileged: true
    tty: true